pyscaffold/configupdater

.cirrus.yml, setup.cfg, src/configupdater/configupdater.py, tests/test_configupdater.py, tox.ini
This is an attempt to start addressing issue #16.
Adding type checking to an untyped codebase is usually a challenge and
sometimes require pragmatic approaches, such as the one adopted in this
commit.
`# type: ignore` and `cast` are used sporadically, but still present when the
type checker is not "smart enough", when the current Python syntax does
not allow expressing the most correct type information or when it was
too hard to introduce it.
It was necessary to remove explicit inheritance from `MuttableMapping`,
since the abstract methods are being overwritten with a non matching
signature that is more convenient for ConfigUpdater.
Functions that use `_UNSET` need to be annotated using `overload`
---
As a quick report, the process used to produce the type annotations was
"semi-manual", …
=> Add type hints (mypy assumed as reference/standard)

LICENSE.txt, src/configupdater/parser.py
After doing the research for https://github.com/pyscaffold/pyscaffold/discussions/459, I came across [Django's license file](https://github.com/django/django/blob/main/LICENSE.python) that references parts of Python (I suppose stdlib) being included/modified in the project.
This commit borrows the same idea (and the variation implemented in PyScaffold's own repo for the 0BSD templates) in an attempt to clarify it follows the PSF redistribution requirements.
=> Add PSF license and note about derivative work

src/configupdater/document.py, src/configupdater/section.py, tests/test_configupdater.py
This is a bug or at least a very strange behavior when using `__setitem__` with a `Document` object. When we do for instance:
```
updater["my_sec"] = Section("other_sec")
```
then we would just overwrite the name "other_sec" with "my_sec" instead of raising an exception that something fishy is going on. This is fixed in this PR by making it consistent to `__setitem__` within a `Section` object where we already raise an exception if the `Option`'s key is not the same as the insertion key.
=> Fix unexpected behavior when adding a secion with __setitem__

src/configupdater/option.py, src/configupdater/parser.py, src/configupdater/section.py
This is a fixed found when looking at the details of PR #35 and its gist in PR #39. 
The problem is that in order to set a value in a new `Option` object one had to do:
```
option = Option(key, value, container=self)
option.value = value
```
which is strange, and inconsistent. The reason for this was that Option is used by the parser and due to multi-line values, an `Option` object can be built incrementally. This is now done with the help of a new method and thus the `Option` object is more user-friendly outside the parser.
=> Fix option object

src/configupdater/document.py, src/configupdater/section.py
Blocks hold a reference to their containers.
If someone for some reason is keeping a reference to a block, and its container is emptied via `.clear()`, it would be nice (for the sake of consistency) to guarantee that the container reference is made `None`.
There is another intriguing aspect: Python GC is based on reference counter... I don't know if keeping ghost references around in the blocks might interfere with that...
=> Detach blocks when cleaning containers

src/configupdater/parser.py
I just found this browsing the code. I guess it was forgotten or is it intended to be like that?
=> Add forgotten return value

CHANGELOG.rst, src/configupdater/parser.py, src/configupdater/section.py, tests/test_configupdater.py
This adds the missing feature of allowing the user to get and set a section comment like
```
[section] # section comment
key  = value
```
as described in #25.
Funny enough it seems that `ConfigParser` doesn't even care if an inline comment is a real comment for sections. This can be seen in this example:
```python
section = """\
[section0] error
key = value
"""
parser = ConfigParser()
parser.read_string(dedent(section))
```
which doesn't raise an error.
=> Allow section comment

src/configupdater/document.py
This is an uncorrelated PR, I just noticed this type hint missing.
=> Add missing type hint to Document.optionxform

src/configupdater/document.py, src/configupdater/option.py, src/configupdater/section.py, tests/test_configupdater.py
This commit should fix #53, expanding on the change proposed in #48.
It should improve consistency in the case the user configures a customised `optionxform` on ConfigUpdater, for 2 reasons:
- If the custom `optionxform` is doing something weird that is incompatible with `str.lower` (e.g. splitting on the first upper case character and joining with `_`), it is better to leave `option.key` alone...
- When importing an option form a different object, the `optionxform` transformation that matters is the one configured in the receiving object, not the one from the source.
Moreover, the added docstrings try to explicit mention all the limitations of the methods.
Obs.: This PR is stacked on top of #52 and already includes the new error case from #53.
=> Improve handling of optionxform when section/option is detached (depends on #52)

README.rst, docs/usage.rst, src/configupdater/block.py, src/configupdater/document.py, src/configupdater/option.py, src/configupdater/section.py, tests/test_configupdater.py
This is the third step to fix #47 and depends on #50 . I am using a technique called [stacked pull requests](https://www.michaelagreiler.com/stacked-pull-requests/) to facilitate the review, which means that merging of the associated PRs in the reverse order makes things easier  😝.
The PR adds some docs regarding `deepcopy`.
I noticed that `usage.rst` and `README.rst` share a lot of common content (in the same way PyScaffold's `README.rst` shares content with its `features.rst`). I suppose this double bookkeeping is because GitHub does not allow rst's `include` directive? I wonder if there is another way of doing that without have to manually sync the files on every change...
=> Document deepcopy usage (4th step towards #47)

README.rst, docs/usage.rst, src/configupdater/block.py, src/configupdater/configupdater.py, src/configupdater/document.py, src/configupdater/option.py, src/configupdater/section.py, tests/test_configupdater.py
This is the third step to fix #47 and depends on #49. I am using a technique called [stacked pull requests](https://www.michaelagreiler.com/stacked-pull-requests/) to facilitate the review, which means that merging of the associated PRs in the reverse order makes things easier  😝.
This is the final `__deepcopy__` implementation refining the `Container.__deepcopy__` behaviour defined in #49 to allow the toplevel `ConfigUpdater` objects to be copied.
=> Deepcopy toplevel (3rd step towards #47)

README.rst, docs/usage.rst, src/configupdater/block.py, src/configupdater/configupdater.py, src/configupdater/container.py, src/configupdater/document.py, src/configupdater/option.py, src/configupdater/section.py, tests/test_configupdater.py, tests/test_section.py
This is the second step to fix #47 and depends on #48. I am using a technique called [stacked pull requests](https://www.michaelagreiler.com/stacked-pull-requests/) to facilitate the review, which means that merging of the associated PRs in the reverse order makes things easier  😝.
Again, I tried to tap into the inheritance chain with auxiliary functions like `_intantiate_copy` and `_copy_structure` to make overwrites possible. This time it was necessary to split `__deepcopy__` into 2 functions because `Section` uses multi-inheritance, so it needs to add the `Container.__deepcopy__` behaviour on top of `Block.__deepcopy__`... The good part is the by doing do `Document` automatically gains access to `deepcopy`.
=> Deepcopy section (2nd step towards #47)

README.rst, docs/usage.rst, src/configupdater/block.py, src/configupdater/configupdater.py, src/configupdater/container.py, src/configupdater/document.py, src/configupdater/option.py, src/configupdater/section.py, tests/test_configupdater.py, tests/test_option.py, tests/test_section.py
This is the first step to fix #47, by implementing `__deepcopy__` on `Option`.
I tried to make use of the inheritance chain (this way `Comment` and `Space` would also be fixed), but since different subclasses have different arguments for `__init__`, I had to add some indirection and an auxiliary `_intantiate_copy` to make overwrites possible.
Moreover this PR also include a fix that allows calling `optionxform` on detached objects. It was very tricky to add a test case without fixing this issue.
=> Deepcopy option (1st step towards #47)

src/configupdater/option.py, src/configupdater/section.py, tests/test_section.py
This change should address https://github.com/pyscaffold/configupdater/pull/53#issuecomment-877594376 and close #53.
---
The other thing I want to do next is to improve a little bit the error messages for `NotAttachedError` and `AlreadyAttachedError` to make it less confusing which block we are refering to (e.g., when adding an option to a detached section the user might think that `NotAttachedError` refers to the option being set, when it actually refers to the section)
=> Remove fallback mechanism for optionxform

src/configupdater/block.py, tests/test_configupdater.py, tests/test_section.py
... this makes it less confusing for users to understand why the error is happening in the case 2 blocks are involved in the same operation (e.g., when adding options to sections). See discussion in #56.
This PR depends on #56.
=> Add reference to block on NotAttached/AlreadyAttachedError message

README.rst, docs/usage.rst, src/configupdater/block.py, src/configupdater/configupdater.py, src/configupdater/container.py, src/configupdater/document.py, src/configupdater/option.py, src/configupdater/section.py, tests/test_configupdater.py, tests/test_option.py, tests/test_section.py
Closes #47
This PR is just a collection of previous ones that were already independently reviewed. No new code was added.
It should address the concerns previously risen, without having to interfere with `optionxform`.
---
The key for the successful implementation of `__deepcopy__` was add `option.raw_key` and calculate the normalised key using the target object's `optionxform` instead of the source object's one.
There is also a small "quality of life improvement" that clarifies which block is the reason for `NotAttachedError` and `AlreadyAttachedError` (so when adding an option to a section, the users can know if the error refers to the option or the section) and other documentation changes.
=> Add deepclone capabilities

README.rst
Somehow `width` and `height` were mixed up in the logo. This could be seen when checking [PyPI](https://pypi.org/project/ConfigUpdater/3.0rc1/).
=> Fix logo scaling in README.rst

src/configupdater/document.py, src/configupdater/option.py, src/configupdater/section.py, tests/test_section.py
I have observed the following usage pattern in PyScaffold's code base:
- Calling `set` on a `Section` object without passing a value
- Calling `set_value` with a list on the same `Option` just afterwards
example:
```python
options.set("install_requires")
options["install_requires"].set_values(deps.RUNTIME)
pyscaffold.set("extensions")
pyscaffold["extensions"].set_values(sorted(old | extensions))
```
The changes proposed here allow passing a list/tuple/sequence/... of strings directly to `set` instead of doing it in 2 stages.
Additionally, I also propagate the changes upwards the chain to `Document.set`.
=> Accept list/tuples/... as values in section.set

src/configupdater/configupdater.py, src/configupdater/document.py, tests/test_configupdater.py
This PR aims to improve the consistency of `ConfigUpdater.__init__` and `ConfigUpdater.validate_format`.
The changes implemented here automatically propagate the `kwargs` used during instantiation to validation.
This is related to a secondary suggestion in #68.
=> Improve consistency of `validate_format`

tools/stdlib-diff.py, tools/stdlib_diff.py, tox.ini
Since ConfigUpdater is initially derived from the stdlib and the stdlib is a moving target, from times to times it is nice to see if there was any improvement that we are not adopting.
When I split the files to try to improve organisation, I made this comparison harder.
This is an attempt to add a tool that will make that job easier for us, even with the files being split.
Examples of how to use this little utility:
```bash
tox -qe py38-diff | delta --side-by-side
tox -qe py39-diff | delta --side-by-side
```
=> Add a diff tool to assist comparing changes to stdlib

src/configupdater/parser.py, src/configupdater/section.py, tests/test_configupdater.py
Fix #92.
It seems that every section is marked as `updated` upon creation because `raw_comment` is assigned using a setter. I modified the `Section` constructor so it can accept the comment directly, avoiding marking the section as updated while it isn't.
When a section isn't marked as updated, the raw line read during parsing is directly re-used for formatting. That means we won't lose indentation in this case. I didn't bother keeping indentation when the section is updated because I noticed it's the case for other objects (like `Option`) to lose indentation also when it's modified. The most important thing is that reading and rewriting without modification leaves the file unchanged, I think.
Preventing the `Section` to be marked as `updated` wasn't enough, because it broke …
=> Fix section losing indentation while not updated

CHANGELOG.rst, src/configupdater/option.py, tests/test_configupdater.py
This addresses the issue #104 and adds a new `prepend_newline` option to `set_values`. By default this option is `True` to reflect the current behaviour. It can be set to `False` to avoid a new line. In this case also the indentation can be automatically determined by passing `None` to `indent`. 
The changes should be 100% backward compatible and should not break anything if `prepend_newline` is not passed or `True`.
=> add a prepend_newline option to set_values

tox.ini
I noticed that the CI was failing on the main because of a missing part in `tox.ini`
(probably because of some failed copy+paste from the latest PyScaffold templates).
=> Update `tox.ini` to include missing actions

README.rst
In #117 it was pointed out that the existing example may lead users to think comments that precede sections belong to those sections (which is not the case).
The idea behind this PR is to fix the example to avoid such interpretation.
=> Reverse order in example to avoid confusion

.readthedocs.yml
`build.os` is now mandatory in `.readthedocs.yml`.
(RTD will not automatically assume that you want the latest ubuntu, which is a deliberate choice from the devs).
See https://github.com/readthedocs/readthedocs.org/issues/8861#issuecomment-1025568797.
=> Fix sphinx config

src/configupdater/document.py
=> Docs: Clarify the `fallback` argument for `ConfigUpdater.get`
